### ISSUE TITLE
请问如何提交三方工具呢？

### ISSUE THREAD

**Issue by MrEasonYang** [flomoapp/3rd-party-tools#56]
没有在本仓库中看到关于如何提交三方工具的相关文档说明，因此开个 issue 咨询下。
是用 PR 的形式改 README 么？格式要求是什么样的呢？

**Comment by lightory** [comment]
自建 Repo，然后在 https://github.com/flomoapp/3rd-party-tools/discussions 这里填写介绍和链接即可。
